vich_uploader:
    db_driver: orm

    mappings:
        song_mix:
            uri_prefix: /mix
            upload_destination: '%kernel.project_dir%/public/mix'
        song_images:
            uri_prefix: /images
            upload_destination: '%kernel.project_dir%/public/images'
